//
// Created by meshi on 13/01/2020.
//

#ifndef FINALPROJECTPART2_MYPARALLELSERVER_H
#define FINALPROJECTPART2_MYPARALLELSERVER_H


class MyParallelServer {

};


#endif //FINALPROJECTPART2_MYPARALLELSERVER_H
